/********************************************************************
* LibHistoManagerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LibHistoManagerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLibHistoManagerDict();
extern void G__cpp_setup_inheritanceLibHistoManagerDict();
extern void G__cpp_setup_typetableLibHistoManagerDict();
extern void G__cpp_setup_memvarLibHistoManagerDict();
extern void G__cpp_setup_globalLibHistoManagerDict();
extern void G__cpp_setup_memfuncLibHistoManagerDict();
extern void G__cpp_setup_funcLibHistoManagerDict();
extern void G__set_cpp_environmentLibHistoManagerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HistoManager.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LibHistoManagerDictLN_TClass;
extern G__linked_taginfo G__LibHistoManagerDictLN_TBuffer;
extern G__linked_taginfo G__LibHistoManagerDictLN_TMemberInspector;
extern G__linked_taginfo G__LibHistoManagerDictLN_TObject;
extern G__linked_taginfo G__LibHistoManagerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_TClonesArray;
extern G__linked_taginfo G__LibHistoManagerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LibHistoManagerDictLN_TH1F;
extern G__linked_taginfo G__LibHistoManagerDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LibHistoManagerDictLN_TProfile;
extern G__linked_taginfo G__LibHistoManagerDictLN_TH2F;
extern G__linked_taginfo G__LibHistoManagerDictLN_TH3F;
extern G__linked_taginfo G__LibHistoManagerDictLN_HistoManager;
extern G__linked_taginfo G__LibHistoManagerDictLN_vectorlEHistDefTH1FcOallocatorlEHistDefTH1FgRsPgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_reverse_iteratorlEvectorlEHistDefTH1FcOallocatorlEHistDefTH1FgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_vectorlEHistDefTH2FcOallocatorlEHistDefTH2FgRsPgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_reverse_iteratorlEvectorlEHistDefTH2FcOallocatorlEHistDefTH2FgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_vectorlEHistDefTProfcOallocatorlEHistDefTProfgRsPgR;
extern G__linked_taginfo G__LibHistoManagerDictLN_reverse_iteratorlEvectorlEHistDefTProfcOallocatorlEHistDefTProfgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
